### ISSUE TITLE
Package Dependencies

### ISSUE THREAD

**Issue by mmuscarella** [odwyer-lab/neutral_progeny_distribution#1]
The code in Neutral_Spec_Rate_MLE.R requires packages which the user may not have. Since packages are currently loaded using `library()`, users missing any of the packages will receive error messages. I suggest using the following to prevent any issues: 

```
packages <- c("hypergeo", "grid", "gridBase", "ggplot2", "plyr", "reshape")
for (i in packages){
  if(!require(i, character.only = T)){
    install.packages(i, dependencies = T)
    require(i, character.only = T)
  }
}
```

**Comment by jodwyer2** [comment]
thanks!
